### ISSUE TITLE
add setting to propagate resources labels and annotations to k8s

### ISSUE THREAD

**Issue by alanngai** [lightbend/sbt-reactive-app#106]
the sbt-reactive-app allows for [additional sbt settings for the project](https://developer.lightbend.com/docs/lightbend-orchestration/current/project-configuration.html).  We should allow an additional setting where the developer can specify arbitrary labels to the resource that will eventually be created.

For example the following setting in the build.sbt

```
labels := Map("team" -> "console"),
annotations := Map(“prometheus.io/scrp” -> True)
```

should map to the following in the generated k8s resource file

```
metadata:
  labels:
    team: console
  annotations:
    prometheus.io/scrp: true
```
