### ISSUE TITLE
HttpIngress config is not being picked-up

### ISSUE THREAD

**Issue by renatocaval** [lightbend/sbt-reactive-app#113]
I added the following to a sample project:

```
endpoints += HttpEndpoint(
  name = "http",
  ingress = HttpIngress(
    ingressPorts = Vector(8080),
    hosts = Vector("akka-grpc.example.org"),
    paths = Vector.empty
  )
)
```

then I generated the docker image and the kubernetes resources

```
> sbt docker:publishLocal
> rp generate-kubernetes-resources --generate-all "akka-grpc-server:0.1.0-SNAPSHOT"
```

The ingress output was:
```
apiVersion: "extensions/v1beta1"
kind: Ingress
metadata:
  name: "akka-grpc-labs"
spec:
  rules:
    - host: "akka-grpc.example.org"
      http:
        paths:
          - backend:
              serviceName: "akka-grpc-labs"
              servicePort: 10000
```

That may be because of my limited kubernetes knowledge, but I was expecting to see port 8080 being added to the yaml file. Instead, it displays the default port 10000.

Next, I changed it to:

```
endpoints += HttpEndpoint(
  name = "http",
  port = 8080,
  ingress = HttpIngress(
    ingressPorts = Vector(8080),
    hosts = Vector("akka-grpc.example.org"),
    paths = Vector.empty
  )
)
```

Port 8080 propagates to all generated files which seems to be correct, but ingress port seems not to be used. Is that the correct behaviour?
