### ISSUE TITLE
container port needs to be settable for monitoring with es-console

### ISSUE THREAD

**Issue by alanngai** [lightbend/sbt-reactive-app#135]
steps to reproduce

1. clone https://github.com/lightbend/es-demos
1. run `sbt iotapp/docker:publishLocal'
1. run `rp generate-kubernetes-resources --generate-all "iotapp:0.1-baseline"`

In the resulting yaml, the container ports isn't specified.  

```
spec:
  template:
    spec:
      containers:
        - name: iotapp
           ports: []
```

As a result, when this container is deployed to minikube, prometheus can't scrape it for cinnamon metrics.  However, if I manually change the yaml to 

```
spec:
  template:
    spec:
      containers:
        - name: iotapp
           ports: 
             - containerPort: 9001
                name: metrics
```

Then prometheus is able to scrape the endpoint correctly.  There doesn't appear to be the affordance to set this at the sbt project level, even though I'm able to set the "prometheus.io/scrape" annotations.

I don't know if there is an elegant way to fix this.  I'm open to suggestions.  I think ideally is that if Cinnamon and prometheus is used, then we'd need to add the container port to the yaml as specified by the `prometheus.io/port` annotation
